export async function GET() {
  return Response.json({
    status: "ok",
    rules: {
      rule: [
        {
          id: 1,
          title: "001",
          color: "n",
          result: null,
        },
        {
          id: 2,
          title: "002",
          color: "n",
          result: null,
        },
        {
          id: 3,
          title: "003",
          color: "n",
          result: null,
        },
        {
          id: 4,
          title: "004",
          color: "n",
          result: null,
        },
        {
          id: 5,
          title: "005",
          color: "n",
          result: null,
        },
        {
          id: 6,
          title: "006",
          color: "n",
          result: null,
        },
        {
          id: 8,
          title: "008",
          color: "n",
          result: null,
        },
        {
          id: 10,
          title: "010",
          color: "n",
          result: null,
        },
        {
          id: 11,
          title: "011",
          color: "n",
          result: null,
        },
        {
          id: 16,
          title: "016",
          color: "n",
          result: null,
        },
        {
          id: 17,
          title: "017",
          color: "n",
          result: null,
        },
        {
          id: 18,
          title: "018",
          color: "n",
          result: null,
        },
        {
          id: 20,
          title: "020",
          color: "n",
          result: null,
        },
        {
          id: 21,
          title: "021",
          color: "n",
          result: null,
        },
        {
          id: 24,
          title: "024",
          color: "n",
          result: null,
        },
        {
          id: 25,
          title: "025",
          color: "n",
          result: null,
        },
        {
          id: 26,
          title: "026",
          color: "n",
          result: null,
        },
        {
          id: 27,
          title: "027",
          color: "n",
          result: null,
        },
        {
          id: 28,
          title: "028",
          color: "n",
          result: null,
        },
        {
          id: 30,
          title: "030",
          color: "n",
          result: null,
        },
        {
          id: 44,
          title: "044",
          color: "n",
          result: null,
        },
        {
          id: 45,
          title: "045",
          color: "n",
          result: null,
        },
        {
          id: 48,
          title: "048",
          color: "n",
          result: null,
        },
        {
          id: 54,
          title: "054",
          color: "n",
          result: null,
        },
        {
          id: 63,
          title: "063",
          color: "n",
          result: null,
        },
        {
          id: 74,
          title: "074",
          color: "n",
          result: null,
        },
        {
          id: 75,
          title: "075",
          color: "n",
          result: null,
        },
        {
          id: 76,
          title: "076",
          color: "n",
          result: null,
        },
        {
          id: 78,
          title: "078",
          color: "n",
          result: null,
        },
        {
          id: 83,
          title: "083",
          color: "n",
          result: null,
        },
        {
          id: 84,
          title: "084",
          color: "n",
          result: null,
        },
        {
          id: 90,
          title: "090",
          color: "n",
          result: null,
        },
        {
          id: 91,
          title: "091",
          color: "n",
          result: null,
        },
        {
          id: 901,
          title: "901",
          color: "n",
          result: null,
        },
      ],
    },
  })
}
