export const ACTIONS = {
  CREATE_ENTITY_LOADING: "CREATE_ENTITY_LOADING",
  CREATE_ENTITY_SUCCESS: "CREATE_ENTITY_SUCCESS",
  CREATE_ENTITY_FAIL: "CREATE_ENTITY_FAIL",

  UPDATE_ENTITY_LOADING: "UPDATE_ENTITY_LOADING",
  UPDATE_ENTITY_SUCCESS: "UPDATE_ENTITY_SUCCESS",
  UPDATE_ENTITY_FAIL: "UPDATE_ENTITY_FAIL",

  DELETE_DEBTOR_ENTITY_LOADING: "DELETE_DEBTOR_ENTITY_LOADING",
  DELETE_DEBTOR_ENTITY_SUCCESS: "DELETE_DEBTOR_ENTITY_SUCCESS",
  DELETE_DEBTOR_ENTITY_FAIL: "DELETE_DEBTOR_ENTITY_FAIL",

  CREATE_DEBTOR_ACCOUNT_LOADING: "CREATE_DEBTOR_ACCOUNT_LOADING",
  CREATE_DEBTOR_ACCOUNT_SUCCESS: "CREATE_DEBTOR_ACCOUNT_SUCCESS",
  CREATE_DEBTOR_ACCOUNT_FAIL: "CREATE_DEBTOR_ACCOUNT_FAIL",

  UPDATE_DEBTOR_ACCOUNT_LOADING: "UPDATE_DEBTOR_ACCOUNT_LOADING",
  UPDATE_DEBTOR_ACCOUNT_SUCCESS: "UPDATE_DEBTOR_ACCOUNT_SUCCESS",
  UPDATE_DEBTOR_ACCOUNT_FAIL: "UPDATE_DEBTOR_ACCOUNT_FAIL",

  // DELETE_DEBTOR_ACCOUNT_LOADING: "DELETE_DEBTOR_ACCOUNT_LOADING",
  // DELETE_DEBTOR_ACCOUNT_SUCCESS: "DELETE_DEBTOR_ACCOUNT_SUCCESS",
  // DELETE_DEBTOR_ACCOUNT_FAIL: "DELETE_DEBTOR_ACCOUNT_FAIL",

  CREATE_CREDITOR_ENTITY_LOADING: "CREATE_CREDITOR_ENTITY_LOADING",
  CREATE_CREDITOR_ENTITY_SUCCESS: "CREATE_CREDITOR_ENTITY_SUCCESS",
  CREATE_CREDITOR_ENTITY_FAIL: "CREATE_CREDITOR_ENTITY_FAIL",

  UPDATE_CREDITOR_ENTITY_LOADING: "UPDATE_CREDITOR_ENTITY_LOADING",
  UPDATE_CREDITOR_ENTITY_SUCCESS: "UPDATE_CREDITOR_ENTITY_SUCCESS",
  UPDATE_CREDITOR_ENTITY_FAIL: "UPDATE_CREDITOR_ENTITY_FAIL",

  DELETE_CREDITOR_ENTITY_LOADING: "DELETE_CREDITOR_ENTITY_LOADING",
  DELETE_CREDITOR_ENTITY_SUCCESS: "DELETE_CREDITOR_ENTITY_SUCCESS",
  DELETE_CREDITOR_ENTITY_FAIL: "DELETE_CREDITOR_ENTITY_FAIL",

  CREATE_CREDITOR_ACCOUNT_LOADING: " CREATE_CREDITOR_ACCOUNT_LOADING",
  CREATE_CREDITOR_ACCOUNT_SUCCESS: " CREATE_CREDITOR_ACCOUNT_SUCCESS",
  CREATE_CREDITOR_ACCOUNT_FAIL: " CREATE_CREDITOR_ACCOUNT_FAIL",

  UPDATE_CREDITOR_ACCOUNT_LOADING: "UPDATE_CREDITOR_ACCOUNT_LOADING",
  UPDATE_CREDITOR_ACCOUNT_SUCCESS: "UPDATE_CREDITOR_ACCOUNT_SUCCESS",
  UPDATE_CREDITOR_ACCOUNT_FAIL: "UPDATE_CREDITOR_ACCOUNT_FAIL",

  // DELETE_CREDITOR_ACCOUNT_LOADING: "DELETE_CREDITOR_ACCOUNT_LOADING",
  // DELETE_CREDITOR_ACCOUNT_SUCCESS: "DELETE_CREDITOR_ACCOUNT_SUCCESS",
  // DELETE_CREDITOR_ACCOUNT_FAIL: "DELETE_CREDITOR_ACCOUNT_FAIL",

  SET_DEBTOR_PACS008_LOADING: "SET_DEBTOR_PACS008_LOADING",
  SET_DEBTOR_PACS008_SUCCESS: "SET_DEBTOR_PACS008_SUCCESS",
  SET_DEBTOR_PACS008_FAIL: "SET_DEBTOR_PACS008_FAIL",

  SET_DEBTOR_ACCOUNT_PACS008_LOADING: "SET_DEBTOR_ACCOUNT_PACS008_LOADING",
  SET_DEBTOR_ACCOUNT_PACS008_SUCCESS: "SET_DEBTOR_ACCOUNT_PACS008_SUCCESS",
  SET_DEBTOR_ACCOUNT_PACS008_FAIL: "SET_DEBTOR_ACCOUNT_PACS008_FAIL",

  SET_CREDITOR_PACS008_LOADING: "SET_CREDITOR_PACS008_LOADING",
  SET_CREDITOR_PACS008_SUCCESS: "SET_CREDITOR_PACS008_SUCCESS",
  SET_CREDITOR_PACS008_FAIL: "SET_CREDITOR_PACS008_FAIL",

  SET_CREDITOR_ACCOUNT_PACS008_LOADING: "SET_CREDITOR_ACCOUNT_PACS008_LOADING",
  SET_CREDITOR_ACCOUNT_PACS008_SUCCESS: "SET_CREDITOR_ACCOUNT_PACS008_SUCCESS",
  SET_CREDITOR_ACCOUNT_PACS008_FAIL: "SET_CREDITOR_ACCOUNT_PACS008_FAIL",

  GENERATE_TRANSACTION_PACS008_LOADING: "GENERATE_TRANSACTION_PACS008_LOADING",
  GENERATE_TRANSACTION_PACS008_SUCCESS: "GENERATE_TRANSACTION_PACS008_SUCCESS",
  GENERATE_TRANSACTION_PACS008_FAIL: "GENERATE_TRANSACTION_PACS008_FAIL",

  UPDATE_TRANSACTION_LOADING: "UPDATE_TRANSACTION_LOADING",
  UPDATE_TRANSACTION_SUCCESS: "UPDATE_TRANSACTION_SUCCESS",
  UPDATE_TRANSACTION_FAIL: "UPDATE_TRANSACTION_FAIL",

  SELECT_DEBTOR_ENTITY: "SELECT_DEBTOR_ENTITY",
  SELECT_CREDITOR_ENTITY: "SELECT_CREDITOR_ENTITY",

  POST_PACS008_LOADING: "POST_PACS008_LOADING",
  POST_PACS008_SUCCESS: "POST_PACS008_SUCCESS",
  POST_PACS008_FAIL: "POST_PACS008_FAIL",

  GENERATE_PACS002_LOADING: "GENERATE_PACS002_LOADING",
  GENERATE_PACS002_SUCCESS: "GENERATE_PACS002_SUCCESS",
  GENERATE_PACS002_FAIL: "GENERATE_PACS002_FAIL",

  POST_PACS002_LOADING: "POST_PACS002_LOADING",
  POST_PACS002_SUCCESS: "POST_PACS002_SUCCESS",
  POST_PACS002_FAIL: "POST_PACS002_FAIL",

  RESET_ENTITY_LOADING: "RESET_ENTITY_LOADING",
  RESET_ENTITY_SUCCESS: "RESET_ENTITY_SUCCESS",
  RESET_ENTITY_FAIL: "RESET_ENTITY_FAIL",

  RESET_CREDITOR_ENTITY_LOADING: "RESET_CREDITOR_ENTITY_LOADING",
  RESET_CREDITOR_ENTITY_SUCCESS: "RESET_CREDITOR_ENTITY_SUCCESS",
  RESET_CREDITOR_ENTITY_FAIL: "RESET_CREDITOR_ENTITY_FAIL",

  SET_RULE_LIGHTS_LOADING: "SET_RULE_LIGHTS_LOADING",
  SET_RULE_LIGHTS_SUCCESS: "SET_RULE_LIGHTS_SUCCESS",
  SET_RULE_LIGHTS_FAIL: "SET_RULE_LIGHTS_FAIL",
  
  CLONE_ENTITY_LOADING: "CLONE_ENTITY_LOADING",
  CLONE_ENTITY_SUCCESS: "CLONE_ENTITY_SUCCESS",
  CLONE_ENTITY_FAIL: "CLONE_ENTITY_FAIL",

  CLONE_CREDITOR_ENTITY_LOADING: "CLONE_CREDITOR_ENTITY_LOADING",
  CLONE_CREDITOR_ENTITY_SUCCESS: "CLONE_CREDITOR_ENTITY_SUCCESS",
  CLONE_CREDITOR_ENTITY_FAIL: "CLONE_CREDITOR_ENTITY_FAIL",

  SET_UI_CONFIG_LOADING: "SET_UI_CONFIG_LOADING",
  SET_UI_CONFIG_SUCCESS: "SET_UI_CONFIG_SUCCESS",
  SET_UI_CONFIG_FAIL: "SET_UI_CONFIG_FAIL",

  UPDATE_STATUS_LOADING: "UPDATE_STATUS_LOADING",
  UPDATE_STATUS_SUCCESS: "UPDATE_STATUS_SUCCESS",
  UPDATE_STATUS_FAIL: "UPDATE_STATUS_FAIL",

}
