export const ACTIONS = {
  CREATE_RULES_LOADING: "CREATE_RULES_LOADING",
  CREATE_RULES_SUCCESS: "CREATE_RULES_SUCCESS",
  CREATE_RULES_FAIL: "CREATE_RULES_FAIL",

  CREATE_TYPO_LOADING: "CREATE_TYPO_LOADING",
  CREATE_TYPO_SUCCESS: "CREATE_TYPO_SUCCESS",
  CREATE_TYPO_FAIL: "CREATE_TYPO_FAIL",

  CREATE_TYPO_EFRUP_LOADING: "CREATE_TYPO_EFRUP_LOADING",
  CREATE_TYPO_EFRUP_SUCCESS: "CREATE_TYPO_EFRUP_SUCCESS",
  CREATE_TYPO_EFRUP_FAIL: "CREATE_TYPO_EFRUP_FAIL",

  SET_TYPO_EFRUP_LOADING: "SET_TYPO_EFRUP_LOADING",
  SET_TYPO_EFRUP_SUCCESS: "SET_TYPO_EFRUP_SUCCESS",
  SET_TYPO_EFRUP_FAIL: "SET_TYPO_EFRUP_FAIL",

  GET_DEBTOR_CONDITIONS_LOADING: "GET_DEBTOR_CONDITIONS_LOADING",
  GET_DEBTOR_CONDITIONS_SUCCESS: "GET_DEBTOR_CONDITIONS_SUCCESS",
  GET_DEBTOR_CONDITIONS_FAIL: "GET_DEBTOR_CONDITIONS_FAIL",

  GET_CREDITOR_CONDITIONS_LOADING: "GET_CREDITOR_CONDITIONS_LOADING",
  GET_CREDITOR_CONDITIONS_SUCCESS: "GET_CREDITOR_CONDITIONS_SUCCESS",
  GET_CREDITOR_CONDITIONS_FAIL: "GET_CREDITOR_CONDITIONS_FAIL",

  ADD_GET_DEBTOR_CONDITIONS_LOADING: "ADD_GET_DEBTOR_CONDITIONS_LOADING",
  ADD_GET_DEBTOR_CONDITIONS_SUCCESS: "ADD_GET_DEBTOR_CONDITIONS_SUCCESS",
  ADD_GET_DEBTOR_CONDITIONS_FAIL: "ADD_GET_DEBTOR_CONDITIONS_FAIL",

  ADD_GET_CREDITOR_CONDITIONS_LOADING: "ADD_GET_CREDITOR_CONDITIONS_LOADING",
  ADD_GET_CREDITOR_CONDITIONS_SUCCESS: "ADD_GET_CREDITOR_CONDITIONS_SUCCESS",
  ADD_GET_CREDITOR_CONDITIONS_FAIL: "ADD_GET_CREDITOR_CONDITIONS_FAIL",

  EXPIRE_CONDITIONS_LOADING: "EXPIRE_CONDITIONS_LOADING",
  EXPIRE_CONDITIONS_SUCCESS: "EXPIRE_CONDITIONS_SUCCESS",
  EXPIRE_CONDITIONS_FAIL: "EXPIRE_CONDITIONS_FAIL",

  CREATE_CONDITIONS_LOADING: "CREATE_CONDITIONS_LOADING",
  CREATE_CONDITIONS_SUCCESS: "CREATE_CONDITIONS_SUCCESS",
  CREATE_CONDITIONS_FAIL: "CREATE_CONDITIONS_FAIL",

  UPDATE_RULES_LOADING: "UPDATE_RULES_LOADING",
  UPDATE_RULES_SUCCESS: "UPDATE_RULES_SUCCESS",
  UPDATE_RULES_FAIL: "UPDATE_RULES_FAIL",

  UPDATE_TYPO_LOADING: "UPDATE_TYPO_LOADING",
  UPDATE_TYPO_SUCCESS: "UPDATE_TYPO_SUCCESS",
  UPDATE_TYPO_FAIL: "UPDATE_TYPO_FAIL",

  UPDATE_TADPROC_LOADING: "UPDATE_TADPROC_LOADING",
  UPDATE_TADPROC_SUCCESS: "UPDATE_TADPROC_SUCCESS",
  UPDATE_TADPROC_FAIL: "UPDATE_TADPROC_FAIL",

  UPDATE_ED_LOADING: "UPDATE_ED_LOADING",
  UPDATE_ED_SUCCESS: "UPDATE_ED_SUCCESS",
  UPDATE_ED_FAIL: "UPDATE_ED_FAIL",

  VALIDATE_RESULTS_LOADING: "VALIDATE_RESULTS_LOADING",
  VALIDATE_RESULTS_SUCCESS: "VALIDATE_RESULTS_SUCCESS",
  VALIDATE_RESULTS_FAIL: "VALIDATE_RESULTS_FAIL",

  SET_TADPROC_RESULTS: "SET_TADPROC_RESULTS",
  RESET_TADPROC_RESULTS: "RESET_TADPROC_RESULTS",
  CLEAR_RESULTS: "CLEAR_RESULTS",

  TURN_RULE_LIGHTS_GREEN: "TURN_RULE_LIGHTS_GREEN",
  TURN_RULE_LIGHTS_NEUTRAL: "TURN_RULE_LIGHTS_NEUTRAL",

  UPDATE_ENTITY_EVENT_TYPE: "UPDATE_ENTITY_EVENT_TYPE",
  UPDATE_ENTITY_ALL_CHECKED: "UPDATE_ENTITY_ALL_CHECKED",

  UPDATE_DEBTOR_ACTIVE_SECTION: "UPDATE_DEBTOR_ACTIVE_SECTION",
  UPDATE_CREDITOR_ACTIVE_SECTION: "UPDATE_CREDITOR_ACTIVE_SECTION",

  SET_SHOW_DEBTOR_CONDITIONS: "SET_SHOW_DEBTOR_CONDITIONS",
  SET_SHOW_CREDITOR_CONDITIONS: "SET_SHOW_CREDITOR_CONDITIONS",

  SET_SHOW_DEBTOR_CONDITIONS_CREATE: "SET_SHOW_DEBTOR_CONDITIONS_CREATE",
  SET_SHOW_CREDITOR_CONDITIONS_CREATE: "SET_SHOW_CREDITOR_CONDITIONS_CREATE",

  SET_APPLICATION_VERSION: "SET_APPLICATION_VERSION",

  SET_LINKED_TYPOLOGIES: "SET_LINKED_TYPOLOGIES",
  CLEAR_LINKED_TYPOLOGIES: "CLEAR_LINKED_TYPOLOGIES",

  RESET_ALL_LIGHTS: "RESET_ALL_LIGHTS",
}
