export const ACTIONS = {
  CREATE_RULES_LOADING: "CREATE_RULES_LOADING",
  CREATE_RULES_SUCCESS: "CREATE_RULES_SUCCESS",
  CREATE_RULES_FAIL: "CREATE_RULES_FAIL",

  CREATE_TYPO_LOADING: "CREATE_TYPO_LOADING",
  CREATE_TYPO_SUCCESS: "CREATE_TYPO_SUCCESS",
  CREATE_TYPO_FAIL: "CREATE_TYPO_FAIL",

  UPDATE_RULES_LOADING: "UPDATE_RULES_LOADING",
  UPDATE_RULES_SUCCESS: "UPDATE_RULES_SUCCESS",
  UPDATE_RULES_FAIL: "UPDATE_RULES_FAIL",

  UPDATE_TYPO_LOADING: "UPDATE_TYPO_LOADING",
  UPDATE_TYPO_SUCCESS: "UPDATE_TYPO_SUCCESS",
  UPDATE_TYPO_FAIL: "UPDATE_TYPO_FAIL",

  UPDATE_TADPROC_LOADING: "UPDATE_TADPROC_LOADING",
  UPDATE_TADPROC_SUCCESS: "UPDATE_TADPROC_SUCCESS",
  UPDATE_TADPROC_FAIL: "UPDATE_TADPROC_FAIL",

  UPDATE_ED_LOADING: "UPDATE_ED_LOADING",
  UPDATE_ED_SUCCESS: "UPDATE_ED_SUCCESS",
  UPDATE_ED_FAIL: "UPDATE_ED_FAIL",

  VALIDATE_RESULTS_LOADING: "VALIDATE_RESULTS_LOADING",
  VALIDATE_RESULTS_SUCCESS: "VALIDATE_RESULTS_SUCCESS",
  VALIDATE_RESULTS_FAIL: "VALIDATE_RESULTS_FAIL",

  SET_TADPROC_RESULTS: "SET_TADPROC_RESULTS",
  RESET_TADPROC_RESULTS: "RESET_TADPROC_RESULTS",

  TURN_RULE_LIGHTS_GREEN: "TURN_RULE_LIGHTS_GREEN",

  RESET_ALL_LIGHTS: "RESET_ALL_LIGHTS",
}
