export async function GET() {
  return Response.json({
    status: "ok",
    types: {
      type: [
        {
          id: 1,
          title: "001",
          color: "n",
          result: null,
        },
        {
          id: 2,
          title: "002",
          color: "n",
          result: null,
        },
        {
          id: 3,
          title: "003",
          color: "n",
          result: null,
        },
        {
          id: 4,
          title: "004",
          color: "n",
          result: null,
        },
        {
          id: 5,
          title: "005",
          color: "n",
          result: null,
        },
        {
          id: 10,
          title: "010",
          color: "n",
          result: null,
        },
        {
          id: 11,
          title: "011",
          color: "n",
          result: null,
        },
        {
          id: 13,
          title: "013",
          color: "n",
          result: null,
        },
        {
          id: 24,
          title: "024",
          color: "n",
          result: null,
        },
        {
          id: 28,
          title: "028",
          color: "n",
          result: null,
        },
        {
          id: 37,
          title: "037",
          color: "n",
          result: null,
        },
        {
          id: 44,
          title: "044",
          color: "n",
          result: null,
        },
        {
          id: 45,
          title: "045",
          color: "n",
          result: null,
        },
        {
          id: 47,
          title: "047",
          color: "n",
          result: null,
        },
        {
          id: 51,
          title: "051",
          color: "n",
          result: null,
        },
        {
          id: 52,
          title: "052",
          color: "n",
          result: null,
        },
        {
          id: 92,
          title: "092",
          color: "n",
          result: null,
        },
        {
          id: 95,
          title: "095",
          color: "n",
          result: null,
        },
        {
          id: 98,
          title: "098",
          color: "n",
          result: null,
        },
        {
          id: 105,
          title: "105",
          color: "n",
          result: null,
        },
        {
          id: 107,
          title: "107",
          color: "n",
          result: null,
        },
        {
          id: 121,
          title: "121",
          color: "n",
          result: null,
        },
        {
          id: 124,
          title: "124",
          color: "n",
          result: null,
        },
        {
          id: 129,
          title: "129",
          color: "n",
          result: null,
        },
        {
          id: 137,
          title: "137",
          color: "n",
          result: null,
        },
        {
          id: 169,
          title: "169",
          color: "n",
          result: null,
        },
        {
          id: 179,
          title: "179",
          color: "n",
          result: null,
        },
        {
          id: 185,
          title: "185",
          color: "n",
          result: null,
        },
        {
          id: 191,
          title: "191",
          color: "n",
          result: null,
        },
        {
          id: 195,
          title: "195",
          color: "n",
          result: null,
        },
        {
          id: 214,
          title: "214",
          color: "n",
          result: null,
        },
        {
          id: 216,
          title: "216",
          color: "n",
          result: null,
        },
        {
          id: 999,
          title: "999",
          color: "n",
          result: null,
        },
      ],
    },
  })
}
